run:
  tests: false

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - dupl
    - goconst
    - gocyclo
    - godot
    - gomnd
    # re-enable once bubbletea is updated
    # - gomoddirectives
    - goprintffuncname
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    #- wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  nestif:
    min-complexity: 10
