name: Build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Test
        # Set TERM variable to force color output
        # Unset CI var because of https://github.com/muesli/termenv/commit/1111971edffa5f9ed2a38bd57f7e434b424f7b29
        run: go build && TERM=xterm-256color CI= script -q -e -c "go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: build examples
        run: ls -d examples/* | xargs sh -c 'cd $0 && go build'
