name: Build
on: [push]
jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
      - name: 'Set up Go'
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: 'build'
        run: |
          go build
